# travis-ci

os: linux
dist: xenial

language: node_js

node_js:
  - "10"
  - "12"
  - "14"
branches:
  only:
    - master
    - trunk/dev
    - trunk/release

script:
  - "npx install-peerdeps --dev --exact eslint-conformance"
  - "yarn run lint"
